CLS
PRINT "Press a key after each tune to continue."
PRINT "Press Ctrl-Break to exit"

PRINT "playing... 1 Mull of Kintyre (sort of)"
    PLAY "l4t200mlo1go2cde..p16msemledcdco1ap48go2cde..p16msemledcd.d"
    PLAY "p32l4t200mlo1go2cde2ceo2dcdefgegfdo1bo2c..mn"
SLEEP

PRINT "playing... 2 Coda"
    PLAY "l8t192o1cp32cl4p32cd#l8gp32gap32al4gl2d"
SLEEP

PRINT "playing... 3 You gotta join."
    PLAY "mbl8t255o2efeg..efeg..efeg.o3c.o2b.a.egmf"
SLEEP

PRINT "playing... 4 You're in the army now."
    PLAY "mbl8t255mso2ea.o3co2b.ae.p8ea.o3co2b.ao3emfmn"
SLEEP

PRINT "playing... 5 Dead March from 'Saul'"
    PLAY "l8t200mlo1c..p16c.p32cp32c.p8e..dp32d.cp32c.o0bo1c..mn"
SLEEP

PRINT "playing... 6 Pink Panther theme."
    PLAY "o2t120l16mbmsel4f.l16el4bl16t100ef.eb.de.db.ao2l4b.l8"
    PLAY "t240gabagemn"
SLEEP

PRINT "playing... 7 Cheerful interludes."
    PLAY "o2l8t255egaageddbcaageccaao3bagfeecco2l4msg..cmn"

    PLAY "o2l8t255gfeddefggfeddefgffddccl4t180f"

    PLAY "o2t255l8eefefeefgfedfeedcbggfedccp8o3cc"
SLEEP

PRINT "playing... 8 Tippy -toe."
    PLAY "o2t255l24cccp32fffp64eeep64gggfffp64aaao3p64cccc"
SLEEP

PRINT "playing... 9 In the Hall of the Mountain King."
    PLAY "o2l4t240;defgafaa;a-ea-a-ge-gg;defgafa;o3dc;o2afa;o3c..p16"
SLEEP

PRINT "playing...10 Pack up your troubles."
    PLAY "o3t255l6cp16l8cp16l16dl8co2b-ab-o3l4cl8ap8l4agl2fdc"
SLEEP

PRINT "playing...11 Rule Britannia."

    PLAY "o3l6t120gt240ga-a-p4t180l8gt180a-gfe-l2dp16l5a+g+l17gfg+fa+"
    PLAY "l16g+gfe-"
SLEEP

PRINT "playing...12 Silly SoftWare Theme"

    PLAY "l8t255o3bo4cdo3bo4co3abgaf#t120gbt200dp8t255o4cdecdo3bo4co3abg"
    PLAY "t120f#at200dp8t255ef#gdef#gef#g#aef#g#ag#abo4co3bo4cdeco3af#gd"
    PLAY "gbt120g"
SLEEP

PRINT "playing...13 I know an Old Lady."

    PLAY "t200o2l8cffaffcl10ff.p64al4fl8gggl4gl8feccl4cl8cl4dl8el3f"
SLEEP

PRINT "playing...14 Hoop-La!"

    PLAY "t240o3l8d#fgl8b-p8l8gl2b-"
SLEEP

PRINT "playing...15 For (s)he's a jolly good fellow."

    PLAY "t240o3l8gfl4el8eedel3fl4el8el4dl8ddcdl3el4cl8dl4e"
    PLAY "l8eedel4fl8gl4al8al4gl8fl4el8dl4c"
SLEEP

PRINT "playing...16 Heigh-ho, said Rowley."

    PLAY "t255o2l8fl4b-l8b-l4fl8fdcdo1l4b-p8o2l3b-o3l4dl8o2b-ao3l4c"
SLEEP

PRINT "playing...17 Dragnet."

    PLAY "t255o2l2cl8dd#p8cp8l2f#"
SLEEP

PRINT "playing...18 Oh my darling, Clementine."

    PLAY "t255o2l8ggl4gdl8bbl4bgl8gbo3l4ddl8co2bl2al8abo3l4cc"
    PLAY "o2l8bal4bgl8bgl4adl8f#al4g"
SLEEP

PRINT "playing...19 The Wedding March."

    PLAY "t240o2l8ggl2gp8l8gggl2gp8l8gggl4bl8bbbl4bl8bbbo3l4dl8ddd"
    PLAY "l4dl8dddl2gl3f#l8c#l4edco2agl8f#gl4al8gal4g"
SLEEP

PRINT "Sound Effects..............................................."

PRINT "playing...20 Assorted Warbles...."

    PLAY "l64t120o3deg#f#ggc#d#edc#ccaa#g#fc#"

    PLAY "t255l16o1abeo2fda"

    PLAY "t255l16o2df#eg#a"

    PLAY "l62o4t250dggdg#aao3dggdaa#a#o2dggda#bb"

    PLAY "mll32o2t255egfd#d#cccc#gc#mn"
SLEEP

PRINT "playing...21 Success."

    PLAY "l8o2t240d..e.p16mlagb."
SLEEP

PRINT "playing...22 Failure (dirge)."

    PLAY "t200o3l4gcdel2fl4ecl2dp64dl4el1c"
SLEEP

PRINT "playing...23 Slither."

    PLAY "t255l15o1adcefao2defaec"
SLEEP

PRINT "playing...24 Discords...."

    PLAY "t255l24o1aaao2bbbo3ccco4dddo5eeeo4dddo3ccco2bbbo1aaa"

    PLAY "t255l16o2cbacbacbacbacbacba"

    PLAY "t255o2l16adadadadadadad"
SLEEP

PRINT "playing...25 Ascending Trill."

    PLAY "t255o1l15deffedo2deffedo3deffedo4deffedo5deffed"
SLEEP

PRINT "playing...26 Descending Trill."

    PLAY "o4l12t255ba#ag#gf#fed#dc#c"
SLEEP

PRINT "playing...27 Up and Down."

    PLAY "t32l64o2cdefgabagfedcdefgabagfed"
SLEEP

PRINT "playing...28 Plunk!"

    PLAY "t255l16o1fo4d#o2fc"
SLEEP

PRINT "playing...29 Plonk!"

    PLAY "t255l16o1bo4dg#o2f"
SLEEP

PRINT "playing...30 Spangle."

    PLAY "O5 L8 T120 F F F F B F B F B F B F B F B F"
END


